version: '3.8'

services:
  java-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-service
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xmx512m
